<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-04T10:51:18 IST" name="Parallel Test Suite" finished-at="2022-11-04T10:51:53 IST" duration-ms="34437">
    <groups>
    </groups>
    <test started-at="2022-11-04T10:51:18 IST" name="Chrome Test" finished-at="2022-11-04T10:51:53 IST" duration-ms="34437">
      <class name="lambdatestjava.LambdaTestJava">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:lambdatestjava.LambdaTestJava@130c12b7]" started-at="2022-11-04T10:51:18 IST" name="setUp" finished-at="2022-11-04T10:51:30 IST" duration-ms="11275" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[86.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[WIN10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testScenario1()[pri:0, instance:lambdatestjava.LambdaTestJava@130c12b7]" started-at="2022-11-04T10:51:30 IST" name="testScenario1" finished-at="2022-11-04T10:51:50 IST" duration-ms="20028" status="FAIL">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method lambdatestjava.LambdaTestJava.testScenario1() didn't finish within the time-out 20000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method lambdatestjava.LambdaTestJava.testScenario1() didn't finish within the time-out 20000
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:350)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:301)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testScenario1 -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:lambdatestjava.LambdaTestJava@130c12b7]" started-at="2022-11-04T10:51:50 IST" name="tearDown" finished-at="2022-11-04T10:51:53 IST" duration-ms="3092" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- lambdatestjava.LambdaTestJava -->
    </test> <!-- Chrome Test -->
  </suite> <!-- Parallel Test Suite -->
</testng-results>
